name: Upload Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@master

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-cli-credentials@v4
        with:
          aws-region: 'us-east-1'
          role-to-assume: arn:aws:iam::533267317699:role/Cloud_Resume_GitHub_Access

      - name: List S3 Buckets
        run: |
          echo "Listing all S3 buckets:"
          aws s3 ls
